import type { CharacterClassDefinition } from './types';

/**
 * Data-driven class registry. To add a new class for players to pick from,
 * append a new `CharacterClassDefinition` here — no other file needs to
 * change. `CharacterSelectScene` and `Player` both read from this array.
 */
export const CLASS_DEFINITIONS: CharacterClassDefinition[] = [
  {
    id: 'warrior',
    name: 'Guerreiro',
    description: 'Especialista em combate corpo a corpo. Muita vida e defesa.',
    color: 0xb33a3a,
    baseStats: {
      maxHp: 32,
      maxMp: 6,
      attack: 9,
      magicAttack: 2,
      defense: 7,
      magicDefense: 3,
      speed: 5,
      luck: 4,
    },
    growth: {
      maxHp: 6,
      maxMp: 1,
      attack: 2,
      magicAttack: 0,
      defense: 2,
      magicDefense: 1,
      speed: 1,
      luck: 1,
    },
    skills: [
      {
        id: 'warrior_power_strike',
        name: 'Golpe Poderoso',
        description: 'Um ataque físico devastador em um inimigo.',
        mpCost: 4,
        target: 'enemy',
        kind: 'physical',
        power: 1.8,
        unlockLevel: 1,
      },
      {
        id: 'warrior_war_cry',
        name: 'Grito de Guerra',
        description: 'Recupera um pouco de vida ao entrar em fúria de combate.',
        mpCost: 5,
        target: 'self',
        kind: 'heal',
        power: 1.2,
        unlockLevel: 4,
      },
    ],
  },
  {
    id: 'mage',
    name: 'Mago',
    description: 'Domina magias ofensivas poderosas, mas é frágil fisicamente.',
    color: 0x3a5fb3,
    baseStats: {
      maxHp: 20,
      maxMp: 24,
      attack: 3,
      magicAttack: 10,
      defense: 3,
      magicDefense: 6,
      speed: 6,
      luck: 5,
    },
    growth: {
      maxHp: 3,
      maxMp: 5,
      attack: 0,
      magicAttack: 3,
      defense: 1,
      magicDefense: 2,
      speed: 1,
      luck: 1,
    },
    skills: [
      {
        id: 'mage_fireball',
        name: 'Bola de Fogo',
        description: 'Lança uma bola de fogo que causa dano mágico.',
        mpCost: 6,
        target: 'enemy',
        kind: 'magical',
        power: 2.2,
        unlockLevel: 1,
      },
      {
        id: 'mage_blizzard',
        name: 'Nevasca',
        description: 'Congela todos os inimigos com dano mágico em área.',
        mpCost: 10,
        target: 'allEnemies',
        kind: 'magical',
        power: 1.3,
        unlockLevel: 5,
      },
    ],
  },
  {
    id: 'archer',
    name: 'Arqueiro',
    description: 'Rápido e preciso, equilibra dano físico e velocidade.',
    color: 0x3fae5b,
    baseStats: {
      maxHp: 26,
      maxMp: 10,
      attack: 8,
      magicAttack: 3,
      defense: 4,
      magicDefense: 4,
      speed: 9,
      luck: 7,
    },
    growth: {
      maxHp: 4,
      maxMp: 2,
      attack: 2,
      magicAttack: 0,
      defense: 1,
      magicDefense: 1,
      speed: 2,
      luck: 2,
    },
    skills: [
      {
        id: 'archer_precise_shot',
        name: 'Tiro Certeiro',
        description: 'Uma flecha certeira com alta chance de acerto crítico.',
        mpCost: 5,
        target: 'enemy',
        kind: 'physical',
        power: 2.0,
        unlockLevel: 1,
      },
      {
        id: 'archer_arrow_rain',
        name: 'Chuva de Flechas',
        description: 'Dispara flechas contra todos os inimigos.',
        mpCost: 9,
        target: 'allEnemies',
        kind: 'physical',
        power: 1.1,
        unlockLevel: 5,
      },
    ],
  },
  {
    id: 'cleric',
    name: 'Clérigo',
    description: 'Suporte devoto, capaz de curar ferimentos e punir inimigos.',
    color: 0xe0c34a,
    baseStats: {
      maxHp: 24,
      maxMp: 20,
      attack: 4,
      magicAttack: 7,
      defense: 5,
      magicDefense: 7,
      speed: 5,
      luck: 6,
    },
    growth: {
      maxHp: 4,
      maxMp: 4,
      attack: 1,
      magicAttack: 2,
      defense: 1,
      magicDefense: 2,
      speed: 1,
      luck: 1,
    },
    skills: [
      {
        id: 'cleric_heal',
        name: 'Cura',
        description: 'Restaura uma boa quantidade de pontos de vida.',
        mpCost: 5,
        target: 'self',
        kind: 'heal',
        power: 2.5,
        unlockLevel: 1,
      },
      {
        id: 'cleric_smite',
        name: 'Julgamento',
        description: 'Invoca energia sagrada contra um inimigo.',
        mpCost: 6,
        target: 'enemy',
        kind: 'magical',
        power: 1.6,
        unlockLevel: 3,
      },
    ],
  },
];

export function getClassById(id: string): CharacterClassDefinition {
  const found = CLASS_DEFINITIONS.find((c) => c.id === id);
  if (!found) {
    throw new Error(`Classe desconhecida: ${id}`);
  }
  return found;
}
